name: Deploy to Netlify Hosting on main merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: ğŸ§° Install Dependencies
        run: npm install
      - name: ğŸ“¦ Build Project
        run: npm run build --if-present
      - name: ğŸ§¹ Run Lint
        run: npm run lint
      - name: ğŸ› Run Tests
        run: npm run test
        env:
          REACT_APP_BITQUERY: ${{ secrets.REACT_APP_BITQUERY }}
          REACT_APP_GETBLOCK: ${{ secrets.REACT_APP_GETBLOCK }}
      - name: ğŸš€ Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          package-manager: npm
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
